name: 发布文件

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  发布APK:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 完全发布
      uses: softprops/action-gh-release@v2
      with:
        files: ayf/*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}